Starting with page 33

## Tensors

In [1]:
import torch
print(torch.cuda.is_available())
print(torch.rand(2,2))

False
tensor([[0.5292, 0.4825],
        [0.9206, 0.0520]])


In [2]:
x = torch.tensor([[0,0,1],
                  [1,1,1],
                  [0,0,0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [3]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
torch.ones(1,2) + torch.ones(1,2)

tensor([[2., 2.]])

In [6]:
torch.rand(1).item()

0.6347964406013489

## Tensor Operations

In [7]:
torch.rand(2,2).max()

tensor(0.7505)

In [8]:
torch.rand(2,2).max().item()

0.9438900947570801

In [9]:
long_tensor = torch.tensor([[0,0,1],
                            [1,1,1],
                            [0,0,0]])
long_tensor.type()

'torch.LongTensor'

In [10]:
float_tensor = long_tensor.to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [13]:
flat_tensor = torch.rand(784)
reshaped_tensor = flat_tensor.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

In [14]:
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
chw_tensor.shape

torch.Size([3, 640, 480])